### ISSUE TITLE
Sketch Beta Version 3.5 (25125) crash when running the Zeplin plugin.

### ISSUE THREAD

**Issue by jacobjarnvall** [zeplin/zeplin-sketch-plugin#10]
Sketch Beta Version 3.5 (25125) crash when running the Zeplin plugin.

**Comment by berkcebi** [comment]
Hey, thanks for letting us know! It actually seems to be working nicely on our end. Might be related to your file, does it happen on each Sketch file or a particular one? Do you mind sharing a little more info, a Sketch file maybe?

Thanks! :pray:

**Comment by jacobjarnvall** [comment]
Hi, sure - what's your email?
Den 14 jan 2016 11:25 fm skrev "Berk Çebi" <notifications@github.com>:
>
> Hey, thanks for letting us know! It actually seems to be working nicely
on our end. Might be related to your file, does it happen on each Sketch
file or a particular one? Do you mind sharing a little more info, a Sketch
file maybe?

**Comment by berkcebi** [comment]
support@zeplin.io
Will check it right away!
