### ISSUE TITLE
Sketch 39 export dont work

### ISSUE THREAD

**Issue by sa6aka** [zeplin/zeplin-sketch-plugin#15]
Sketch 39 beta is out but Zeplin doesn't support it.

**Comment by constantx** [comment]
confirmed. Zeplin keeps crashing during export.

**Comment by inosaint** [comment]
Crashing for me after the Sketch 39.1 update as well.

**Comment by berkcebi** [comment]
Hey hey, this was actually fixed about a month ago. Mind giving it a try with Zeplin's latest version? (From the menu up top: Zeplin > Check for Updates…)

**Comment by inosaint** [comment]
@berkcebi Thanks, I got it working. My 1.5.3 was not showing new updates were available.

**Comment by berkcebi** [comment]
Closing this one - let me know if you still have any issues!
