### ISSUE TITLE
Mark project with priority badge (Feature request)

### ISSUE THREAD

**Issue by vadivelMT** [zeplin/zeplin-sketch-plugin#17]
We are using a starter plan(3 active projects) in our office. By means we have to active / archive the projects too often than normal usage. Even though it is a click of a button, but one has to cross check with other member whether they can activate / archive the certain project. And it takes a long time if you consider it is being done often. I would suggest to have a badge which says "Important" or something similar to that will help us. 

If you ask me to select the next plan, I am sorry we can't afford that :)

**Comment by borulday** [comment]
Hi, I'm closing this issue because it has been outdated.

Please send your feedback and feature requests directly to [support@zeplin.io](mailto:support@zeplin.io).

Thank you!
