### ISSUE TITLE
Zeplin Photoshop plugin not working 

### ISSUE THREAD

**Issue by anil826** [zeplin/zeplin-sketch-plugin#18]
I install the https://medium.com/zeplin-gazette/photoshop-open-beta-now-3f8f502fc4de#.wi07d5fl7.

But not its not showing the export button after selection.
![screen shot 2016-10-20 at 1 41 39 am](https://cloud.githubusercontent.com/assets/7324027/19535785/c31293e8-9666-11e6-8b2a-f4d7b186edc0.png)

**Comment by he4amm** [comment]
I've the same problem here. Did you figure it out?

**Comment by canoztokmak** [comment]
Hey @anil826,
It looks like you don't have an artboard in your PS file. If you convert your design to artboard, you'll see the big orange export button.

**Comment by anil826** [comment]
Hi guys,
I fixed the problem It's not working because the pluging is not installed properly once I re-install the pluging then it's working for me .
Go below link for steps..
https://medium.com/zeplin-gazette/photoshop-open-beta-now-3f8f502fc4de#.vgoxclc6a
