### ISSUE TITLE
[Feature Request] Commit message on export

### ISSUE THREAD

**Issue by jordanhbraun** [zeplin/zeplin-sketch-plugin#32]
Prompt for optional commit message that would apply to all selected artboards.

**Comment by jordenchang55** [comment]
+1

**Comment by kardeslik** [comment]
This has been released with Zeplin App Version 2.6

![image](https://user-images.githubusercontent.com/2386588/61781445-04cf1980-ae0d-11e9-8bc4-afd579156fc0.png)

To update your Mac app, click "Zeplin > Check for Updates…". If you don't have the app, you can download it from [here](https://zpl.io/download-mac).
