### ISSUE TITLE
Zeplin plugin not compatible with sketch 71

### ISSUE THREAD

**Issue by vicenteocana** [zeplin/zeplin-sketch-plugin#49]

**Comment by vicenteocana** [comment]
I just upgraded to Sketch 71 and suddenly plugin has been deactivated, warning " this plugin is incompatible with sketch 71".

Version 1.9

**Comment by mmeester** [comment]
You can just use it, enable it in your plugins panel (you might need to restart sketch) and use it.

**Comment by borulday** [comment]
Closing this one since the plugin is no more incompatible.
